### ISSUE TITLE
Librerías necesarias para GLMM

### ISSUE THREAD

**Issue by nepito** [IslasGECI/docker#1]
Necesitamos estas librerías de :r: para hacer el análisis necesarios de éxito de volantón:
`car`, `emmeans`, `ggpubr`, `lme4` y `MuMIn`. Estás librerías no están en [aquí](http://islasgeci.org:8888/lab?).

**Comment by devarops** [comment]
@nepito: ¿Crees que esto va en este repo o en [GLMM (GitHub)](https://github.com/IslasGECI/glmm) o [GLMM (Docker Hub)](https://hub.docker.com/repository/docker/islasgeci/glmm)

**Comment by nepito** [comment]
Sospecho que debe de ir en la primera opción: [GLMM (GitHub)](https://github.com/IslasGECI/glmm).
Lo acabo de crear [allá](https://github.com/IslasGECI/glmm/issues/1), ¿borro este?
